version: '3'

services:
  BilmoDB:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306:3306'
  phpMyAdmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: BilmoPMA
    links:
      - BilmoDB
    environment:
      PMA_HOST: 'BilmoDB'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8083:80